### ISSUE TITLE
markdown-файлы вместо комментариев

### ISSUE THREAD

**Issue by SirojiddinSaidmurodov** [YaphetS7/OOAP#1]
В OOAP/Warcraft3_design вместо *.java файлов без исполняемого кода, предлагаю писать описание (документацию?) в *.md файлах, так как гитхаб README.md файлы выводит текстом в любых подкаталогах

**Comment by YaphetS7** [comment]
> В OOAP/Warcraft3_design вместо *.java файлов без исполняемого кода, предлагаю писать описание (документацию?) в *.md файлах, так как гитхаб README.md файлы выводит текстом в любых подкаталогах

Солидарен, жду второй пул реквест к сегодняшнему коммиту :D

**Comment by SirojiddinSaidmurodov** [comment]
Окей
